GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTcyNTM1NjU5MH0.ZnWP6RDHGYwcv3Al_8-FDL-825Cr1Ek0wCkf-EPMNdk

###

DELETE http://localhost:4000/logut
Content-Type: application/json

{
    "token":"fgherwighewiuogjewiogewji"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"fgherwighewiuogjewiogewji"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Kyle"
}
